name: Release new version

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to release'
            required: true
        pack_format:
            description: 'Pack format to release'
            required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Replace the pack format
        run: sed -i "s/PACK_VERSION/${{ github.event.inputs.pack_format }}/g" "Remove Christmas Chests/pack.mcmeta"
      - run: cd "Remove Christmas Chests" && zip -qq -r ../RemoveChristmasChests-${{ github.event.inputs.version }}.zip .
        name: Zip up the pack
      - name: Save the zip as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: RemoveChristmasChests-${{ github.event.inputs.version }}.zip
          path: |
            RemoveChristmasChests-${{ github.event.inputs.version }}.zip
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ secrets.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: minecraft
          version-type: release
          game-version: |
            >=${{ github.event.inputs.version }}
