name: Release new version

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Minecraft version to release for'
            required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zip
        uses: montudor/action-zip@v1
      - run: cd "Remove Christmas Chests" && zip -qq -r ../RemoveChristmasChests-${{ github.event.inputs.version }}.zip .
        name: Zip up the pack
      - name: Save the zip as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: RemoveChristmasChests-${{ github.event.inputs.version }}.zip
          path: |
            RemoveChristmasChests-${{ github.event.inputs.version }}.zip
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: Remove Christmas Chests for ${{ github.event.inputs.version }}

          curseforge-id: ${{ secrets.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: minecraft
          version: ${{ github.event.inputs.version }}
          version-type: release
          files: |
            RemoveChristmasChests-${{ github.event.inputs.version }}.zip
          game-versions: |
            >=${{ github.event.inputs.version }}
